baseURL = 'http://quartinus.github.io/'
languageCode = 'en-us'
title = "Kira and Duncan's Homepage"
theme = 'hugo-theme-massively'
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]


[languages]
[languages.en]
  languageName = "English"